const prompt = require('prompt-sync')();
const msg = "Hello World"
const lnha = ("=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=")
let confirm = ''
console.log(lnha)
console.log(msg)
console.log(lnha)
console.log('')
console.log('Olá, este é um sistema que está em processo\nde desenvolvimento, sua ajuda poderia ser\nmuito útil para esse proceso.\nVamos Começar?')
console.log('')
let nome = prompt('Qual seu nome? ')
let sobreNome = prompt('Sobrenome? ')
let cidade = prompt('De qual cidade você é? ')
let cep = parseInt(prompt('Cep: '))
let tel = +prompt('Telefone: ')
console.log('')
console.log('')
console.log(lnha)
console.log('Obrigado por responder!')
console.log(`Então seus dados são:`)
console.log(`Nome: ${nome} ${sobreNome}`)
console.log(`Cidade: ${cidade}`)
console.log(`CEP: ${cep} Telefone: ${tel}`)
confirm = prompt('Estão corretos? [S/N]')